version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - FIGMA_API_KEY=${FIGMA_API_KEY}
      - MLFLOW_API_URL=http://mlflow-serve:5001/invocations
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mlflow-serve
    restart: always

  mlflow-serve:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    restart: always